
export enum UserMutationTypes {
  SET_TOKEN = 'SET_TOKEN',
  SET_USERNAME = 'SET_USERNAME',
  SET_MOBILE = 'SET_MOBILE',
  SET_EMAIL = 'SET_EMAIL',
  SET_AVATAR = 'SET_AVATAR',
  SET_REMARKS = 'SET_REMARKS',
  SET_SEX = 'SET_SEX',
}